### ISSUE TITLE
Cannot read property 'resize' of undefined

### ISSUE THREAD

**Issue by WimSuenensDIRACIndustries** [DanieLeeuwner/JSZPL#7]
Getting the following error while calling label.generateZPL().
<img width="928" alt="Screenshot 2020-02-10 at 16 03 46" src="https://user-images.githubusercontent.com/45723129/74161990-39c38200-4c20-11ea-9a88-9dd2e3f44063.png">

**Comment by nafiln** [comment]
Getting the same error while using the Image. Although following the exact code

**Comment by DiscoStarslayer** [comment]
I have also hit this error when trying to run the project. For some reason `LabelTools.ImageResizer` is never initialized in the current release.

Doing the following fixes the issue:
```js
jszpl.LabelTools.ImageResizer = new jszpl.ImageResizer();
```

I have a feeling this is a bug, but I'm not sure where the image resizer should be initialized 🤔

**Comment by DanieLeeuwner** [comment]
As correctly noted by @DiscoStarslayer, this is due to some items not initializing. 

These items should be initialized as shown in the demo designer.js file: https://github.com/DanieLeeuwner/JSZPL/blob/70a9c99fcbb961385bf54e189cb7051205c3c55d/demo/designer.js#L522-L524

This is clearly an issue that will be resolved in a future release by assigning these processors as defaults.

**Comment by DanieLeeuwner** [comment]
Tools added by default in latest commit (c6c0e158f72880e4998f9c8b9274ed2677729f8e).
